new start script, swapped json for dkjson

diff --git a/bin/busted b/bin/busted
--- a/bin/busted
+++ b/bin/busted
@@ -1,32 +1,15 @@
-#!/usr/bin/env lua
+#!/bin/sh
+BUSTED=$BASH_SOURCE"_bootstrap.lua"
+commandExists () {
+    command -v "$1" &> /dev/null ;
+}
 
--- Busted command-line runner
-
-package.path = './?.lua;'..package.path
-
-busted = require 'busted'
-
-local cli = require("cliargs")
-
-cli:set_name("test")
-cli:add_argument("ROOT", "test script file")
-cli:add_flag("--version", "prints the program's version and exits")
-cli:add_option("-v", "verbose output of errors")
-cli:add_option("-c, --color", "disable colored output")
-cli:add_option("-j, --json", "json output")
-
-local args = cli:parse_args()
-
-if args then 
-  if args["version"] then
-    return print("test.lua: version 0.0.0")
-  end
-
-  loadfile(args["ROOT"])()
-
-  print(busted({ 
-    verbose = args["v"] ~= "",
-    color = args["c"] == "",
-    json = args["j"] ~= "",
-  }))
-end
+if commandExists luajit ; then
+  COMMAND=luajit;
+elif commandExists lua ; then
+  COMMAND=lua;
+else
+  echo >&2 "Busted requires that either lua or luajit be installed and accessible via your path. Aborting.";
+  exit 1
+fi
+$COMMAND $BUSTED $*;
